# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macOS-10.15'

steps:
- task: CocoaPods@0
  inputs:
    workingDirectory: '$(Build.SourcesDirectory)'
    forceRepoUpdate: false
    projectDirectory: '$(Build.SourcesDirectory)'
- task: Xcode@5
  inputs:
    actions: 'build'
    configuration: 'Release'
    sdk: 'iphoneos'
    xcWorkspacePath: '$(Build.SourcesDirectory)/swiftapp.xcodeproj/project.xcworkspace'
    packageApp: true
    publishJUnitResults: true
